# -*- coding: utf-8 -*-
"""matplotlib.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cjHU6JTv6GnbrBQdGvwSy_xSDfg1aijg
"""

import matplotlib.pyplot as plt
import numpy as np

"""**Draw a line in a diagram from position (0,0) to position (6,250):**"""

x = np.array([0,6])
y = np.array([0,250])

plt.plot(x,y)
print(plt.show())

"""# plotting without line:"""

plt.plot(x,y, 'o')
plt.show()

"""**multiplw point:**"""

x = np.array([1,2,6,8])
y = np.array([3,8,1,10])

plt.plot(x,y)
plt.show()

x = np.array([1,2,6,8])
y = np.array([3,8,1,10])

plt.plot(x,y, marker = 'o')
plt.show()

x = np.array([1,2,6,8])
y = np.array([3,8,1,10])

plt.plot(x,y, marker = '*')
plt.show()

"""**marker|line|color**"""

x = np.array([1,2,6,8])
y = np.array([3,8,1,10])

plt.plot(x,y,'*-.m')
plt.show()

"""**Set the size of the markers to 20: MS = markersize**"""

x = np.array([1,2,6,8])
y = np.array([3,8,1,10])

plt.plot(x,y,'*-.m',ms = 20)
plt.show()

"""**Set the EDGE color to blue: mec = markeredgecolor**"""

x = np.array([1,2,6,8])
y = np.array([3,8,1,10])

plt.plot(x,y,'*-.m',ms = 20,mec = 'b')
plt.show()

"""**Set the FACE color to green: mfc = markerfacecolor**"""

x = np.array([1,2,6,8])
y = np.array([3,8,1,10])

plt.plot(x,y,'*-.m',ms = 20,mec = 'b',mfc = 'g')
plt.show()

"""# **Line Style:**

**ls/linestye:**
"""

x = np.array([1,2,3,5])
y = np.array([3,8,1,10])

plt.plot(x,y,'*m',ms = 20,mec = 'b',mfc = 'g',ls = 'dotted')
plt.show()

"""**linewidth:**"""

x = np.array([1,2,6,8])
y = np.array([3,8,1,10])

plt.plot(x,y,'*m',ms = 20,mec = 'b',ls = 'dotted',lw = '20')
plt.show()

"""**multiple line:**"""

x1 = np.array([1,2,3,5])
y1 = np.array([3,8,1,10])

x2 = np.array([2,6,0,3])
y2 = np.array([7,10,11,12])


plt.plot(x1,y1,'*m',ms = 20,mec = 'b',mfc = 'g',ls = 'dotted')
plt.plot(x2,y2,marker = 'o', c = 'r',ms = 20,mec = 'b',mfc = 'g')

plt.show()

x = np.array([8, 8, 9, 9, 10, 10, 11, 11, 12, 12])
y = np.array([2, 20, 26, 27, 28, 29, 30, 31, 32, 33])

plt.title("Sports Watch Data", loc = 'left')
plt.xlabel("Average Pulse")
plt.ylabel("Calorie Burnage")

plt.plot(x, y)
plt.show()

"""**Grid:**"""

x = np.array([8, 8, 9, 9, 10, 10, 11, 11, 12, 12])
y = np.array([2, 20, 26, 27, 28, 29, 30, 31, 32, 33])

plt.xlabel('Avarage Pulse')
plt.ylabel('Calorie Burnage')
plt.title('Sports Watch Data')

plt.plot(x,y,c = 'm')
plt.grid()
plt.show()

x = np.array([8, 8, 9, 9, 10, 10, 11, 11, 12, 12])
y = np.array([2, 20, 26, 27, 28, 29, 30, 31, 32, 33])

plt.xlabel('Avarage Pulse')
plt.ylabel('Calorie Burnage')
plt.title('Sports Watch Data')

plt.plot(x,y,c = 'm')
plt.grid(axis = 'x')
plt.show()

"""**Subplot:**"""

x1 = np.array([0,1,2,3])
y1 = np.array([3,8,1,10])

plt.subplot(1,2,1)
plt.plot(x1,y1)

x2 = np.array([0,1,2,3])
y2 = np.array([10,20,30,40])

plt.subplot(1,2,2)
plt.plot(x2,y2)

plt.show()

x1 = np.array([0,1,2,3])
y1 = np.array([3,8,1,10])

plt.subplot(2,1,1)
plt.plot(x1,y1)

x2 = np.array([0,1,2,3])
y2 = np.array([10,20,30,40])

plt.subplot(2,1,2)
plt.plot(x2,y2)

plt.show()

x = np.array([0,1,2,3])
y = np.array([3,8,1,10])

plt.subplot(2,3,1)
plt.plot(x,y,c = 'm')
plt.title("Saimim")

x = np.array([0,1,2,3])
y = np.array([10,20,30,40])

plt.subplot(2,3,2)
plt.plot(x,y, c = 'r')
plt.title("Abid")

x = np.array([0,1,2,3])
y = np.array([3,8,1,10])

plt.subplot(2,3,3)
plt.plot(x,y, c = 'b')
plt.title("Istiaq")

x = np.array([0,1,2,3])
y = np.array([10,20,30,40])

plt.subplot(2,3,4)
plt.plot(x,y,c = 'g')
plt.title("Tithy")

x = np.array([0,1,2,3])
y = np.array([3,8,1,10])

plt.subplot(2,3,5)
plt.plot(x,y,'*:', mec = 'r')
plt.title("Islam", loc = 'left')

plt.suptitle("Students")

plt.show()

"""**Scatter Diagram:**"""

x = np.array([5,7,8,7,2,17,2,9,4,11,12,9,6])
y = np.array([99,86,87,88,111,86,103,87,94,78,77,85,86])
plt.scatter(x,y)
plt.show()

x = np.array([5,7,8,7,2,17,2,9,4,11,12,9,6])
y = np.array([99,86,87,88,111,86,103,87,94,78,77,85,86])
colors = np.array([0, 10, 20, 30, 40, 45, 50, 55, 60, 70, 80, 90, 100])

plt.scatter(x, y, c=colors, cmap='viridis')

plt.colorbar()

plt.show()

"""**Bar:**"""

x = np.array(['A','B','C','D'])
y = np.array([3,8,1,10])

plt.bar(x,y)
plt.show()

x = np.array(['A','B','C','D'])
y = np.array([3,8,1,10])

plt.bar(x,y,width = 0.1)
plt.show()

"""**Histogram:**"""

x = np.array([5,7,8,7,2,17,2,9,4,11,12,9,6])
plt.hist(x,color ='r')
plt.title("Saimim",loc = 'right')
plt.show()

"""**Pie Chart:**
x/sum(x)
"""

y = np.array([35,25,15])
plt.pie(y)
plt.show()

"""with label"""

y = np.array([35,25,25,15])
mylabels = ['Apples','Bananas','Cherries','Dates']

plt.pie(y, labels = mylabels)
plt.show()

"""**Manual Startangel:**"""

y = np.array([35,25,25,15])
mylabels = ['Apples','Bananas','Cherries','Dates']

plt.pie(y,labels = mylabels, startangle = 90)
plt.show()

y = np.array([35,25,25,15])
mylabels = ['Apples','Bananas','Cherries','Dates']
myexplode = [0.2,0,0,0]

plt.pie(y,labels = mylabels, startangle = 90, explode = myexplode)
plt.show()

y = np.array([35,25,25,15])
mylabels = ['Apples','Bananas','Cherries','Dates']
myexplode = [0.2,0,0,0]

plt.pie(y,labels = mylabels, startangle = 90, explode = myexplode, shadow = True)
plt.show()

y = np.array([35,25,25,15])
mylabels = ['Apples','Bananas','Cherries','Dates']
myexplode = [0.2,0,0,0]
clr = ["black", "hotpink", "b", "m"]

plt.pie(y,labels = mylabels, startangle = 90, explode = myexplode, shadow = True, colors = clr)
plt.show()

y = np.array([35,25,25,15])
mylabels = ['Apples','Bananas','Cherries','Dates']
myexplode = [0.2,0,0,0]
clr = ["black", "hotpink", "b", "m"]

plt.pie(y,labels = mylabels, startangle = 90, explode = myexplode, shadow = True, colors = clr)
plt.legend(title = 'Four Fruits')
plt.show()